<?php

declare(strict_types=1);

/**
 * @copyright Copyright (c) 2020 Daniel Kesselberg <mail@danielkesselberg.de>
 *
 * @author Daniel Kesselberg <mail@danielkesselberg.de>
 *
 * @license GNU AGPL version 3 or any later version
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 */

namespace OCA\ServerInfo\Tests;

use OCA\ServerInfo\OperatingSystems\Dummy;
use PHPUnit\Framework\MockObject\MockObject;
use Test\TestCase;

class DummyTest extends TestCase {
	/** @var Dummy|MockObject */
	protected $os;

	protected function setUp(): void {
		parent::setUp(); // TODO: Change the autogenerated stub

		$this->os = new Dummy();
	}

	public function testGetMemory(): void {
		$memory = $this->os->getMemory();

		$this->assertEquals(-1, $memory->getMemTotal());
		$this->assertEquals(-1, $memory->getMemFree());
		$this->assertEquals(-1, $memory->getMemAvailable());
		$this->assertEquals(-1, $memory->getSwapTotal());
		$this->assertEquals(-1, $memory->getSwapFree());
	}

	public function testGetCpuName(): void {
		$this->assertEquals('Unknown Processor', $this->os->getCpuName());
	}

	public function testGetUptime(): void {
		$this->assertEquals(-1, $this->os->getUptime());
	}


	public function testGetDiskInfo(): void {
		$this->assertEquals([], $this->os->getDiskInfo());
	}

	public function testSupported(): void {
		$this->assertFalse($this->os->supported());
	}

	public function testGetNetworkInterfaces(): void {
		$this->assertEquals([], $this->os->getNetworkInterfaces());
	}
}
