<?php

declare(strict_types=1);

/**
 * SPDX-FileCopyrightText: 2020 Nextcloud GmbH and Nextcloud contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

namespace OCA\ServerInfo\Tests;

use OCA\ServerInfo\OperatingSystems\Dummy;
use PHPUnit\Framework\MockObject\MockObject;
use Test\TestCase;

class DummyTest extends TestCase {
	/** @var Dummy|MockObject */
	protected $os;

	protected function setUp(): void {
		parent::setUp(); // TODO: Change the autogenerated stub

		$this->os = new Dummy();
	}

	public function testGetCpu(): void {
		$cpu = $this->os->getCPU();

		$this->assertEquals('Unknown Processor', $cpu->getName());
		$this->assertEquals(1, $cpu->getThreads());
	}

	public function testGetMemory(): void {
		$memory = $this->os->getMemory();

		$this->assertEquals(-1, $memory->getMemTotal());
		$this->assertEquals(-1, $memory->getMemFree());
		$this->assertEquals(-1, $memory->getMemAvailable());
		$this->assertEquals(-1, $memory->getSwapTotal());
		$this->assertEquals(-1, $memory->getSwapFree());
	}

	public function testGetUptime(): void {
		$this->assertEquals(-1, $this->os->getUptime());
	}


	public function testGetDiskInfo(): void {
		$this->assertEquals([], $this->os->getDiskInfo());
	}

	public function testSupported(): void {
		$this->assertFalse($this->os->supported());
	}

	public function testGetNetworkInterfaces(): void {
		$this->assertEquals([], $this->os->getNetworkInterfaces());
	}
}
